<a href="https://colab.research.google.com/github/vasanthi2469/Python-Training/blob/main/DAY-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.6)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/daniellopez01/credit-risk")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: vanisanthoshi
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/daniellopez01/credit-risk
Downloading credit-risk.zip to ./credit-risk

100%|██████████| 13.4k/13.4k [00:00<00:00, 6.32MB/s]

In [4]:
import pandas as pd
data = pd.read_csv('/content/credit-risk/credit.csv')

In [5]:
data.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_duration,percent_of_income,years_at_residence,age,other_credit,housing,existing_loans_count,job,dependents,phone,default
0,< 0 DM,6,critical,furniture/appliances,1169,unknown,> 7 years,4,4,67,none,own,2,skilled,1,yes,no
1,1 - 200 DM,48,good,furniture/appliances,5951,< 100 DM,1 - 4 years,2,2,22,none,own,1,skilled,1,no,yes
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 years,2,3,49,none,own,1,unskilled,2,no,no
3,< 0 DM,42,good,furniture/appliances,7882,< 100 DM,4 - 7 years,2,4,45,none,other,1,skilled,2,no,no
4,< 0 DM,24,poor,car,4870,< 100 DM,1 - 4 years,3,4,53,none,other,2,skilled,2,no,yes

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skew
import statistics

# Assuming the data is already loaded in a DataFrame named 'df'

# Statistical Measures for Numerical Data
numerical_columns = ["months_loan_duration", "amount", "percent_of_income", "years_at_residence", "age", "existing_loans_count", "dependents"]
print("Numerical Data Summary:")

for col in numerical_columns:
    print(f"\n{col}:")
    mean = statistics.mean(df[col])
    median = statistics.median(df[col])
    data_range = max(df[col]) - min(df[col])
    data_skewness = skew(df[col])
    variance = np.var(df[col], ddof=1)  # Using sample variance (ddof=1)
    std_deviation = np.std(df[col], ddof=1)  # Sample standard deviation

    print(f"Mean: {mean}")
    print(f"Median: {median}")
    print(f"Range: {data_range}")
    print(f"Skewness: {data_skewness}")
    print(f"Variance: {variance}")
    print(f"Standard Deviation: {std_deviation}")

# Outlier Detection (using Z-score method for numerical columns)
def detect_outliers(data):
    z_scores = [(x - np.mean(data)) / np.std(data) for x in data]
    outliers = [x for x, z in zip(data, z_scores) if abs(z) > 3]
    return outliers

for col in numerical_columns:
    outliers = detect_outliers(df[col])
    print(f"Outliers in {col}: {outliers}")

# Categorical Data Analysis (Frequency & Mode)
categorical_columns = ["checking_balance", "credit_history", "purpose", "savings_balance", "employment_duration", "other_credit", "housing", "job", "phone", "default"]
print("\nCategorical Data Summary:")

for col in categorical_columns:
    print(f"\n{col}:")
    mode = statistics.mode(df[col])
    value_counts = df[col].value_counts()

    print(f"Mode: {mode}")
    print(f"Value Counts:\n{value_counts}")

Numerical Data Summary:

months_loan_duration:
Mean: 26.4
Median: 24
Range: 42
Skewness: 0.10880269824164941
Variance: 334.8
Standard Deviation: 18.297540818372287

amount:
Mean: 4393.6
Median: 4870
Range: 6713
Skewness: 0.00899069949878133
Variance: 7624599.300000001
Standard Deviation: 2761.267697996701

percent_of_income:
Mean: 2.6
Median: 2
Range: 2
Skewness: 0.8437499999999996
Variance: 0.8
Standard Deviation: 0.8944271909999159

years_at_residence:
Mean: 3.4
Median: 4
Range: 2
Skewness: -0.8437499999999996
Variance: 0.8
Standard Deviation: 0.8944271909999159

age:
Mean: 47.2
Median: 49
Range: 45
Skewness: -0.5151734562458539
Variance: 267.2
Standard Deviation: 16.34625339336204

existing_loans_count:
Mean: 1.4
Median: 1
Range: 1
Skewness: 0.4082482904638635
Variance: 0.3
Standard Deviation: 0.5477225575051661

dependents:
Mean: 1.6
Median: 2
Range: 1
Skewness: -0.4082482904638636
Variance: 0.3
Standard Deviation: 0.5477225575051661
Outliers in months_loan_duration: []
Outliers in amount: []
Outliers in percent_of_income: []
Outliers in years_at_residence: []
Outliers in age: []
Outliers in existing_loans_count: []
Outliers in dependents: []

Categorical Data Summary:

checking_balance:
Mode: < 0 DM
Value Counts:
checking_balance
< 0 DM        3
1 - 200 DM    1
unknown       1
Name: count, dtype: int64

credit_history:
Mode: critical
Value Counts:
credit_history
critical    2
good        2
poor        1
Name: count, dtype: int64

purpose:
Mode: furniture/appliances
Value Counts:
purpose
furniture/appliances    3
education               1
car                     1
Name: count, dtype: int64

savings_balance:
Mode: < 100 DM
Value Counts:
savings_balance
< 100 DM    4
unknown     1
Name: count, dtype: int64

employment_duration:
Mode: 1 - 4 years
Value Counts:
employment_duration
1 - 4 years    2
4 - 7 years    2
> 7 years      1
Name: count, dtype: int64

other_credit:
Mode: none
Value Counts:
other_credit
none    5
Name: count, dtype: int64

housing:
Mode: own
Value Counts:
housing
own      3
other    2
Name: count, dtype: int64

job:
Mode: skilled
Value Counts:
job
skilled      4
unskilled    1
Name: count, dtype: int64

phone:
Mode: no
Value Counts:
phone
no     3
yes    2
Name: count, dtype: int64

default:
Mode: no
Value Counts:
default
no     3
yes    2
Name: count, dtype: int64